### ISSUE TITLE
Prometheus stepsConsumer raising type error for step duration

### ISSUE THREAD

**Issue by heytred** [claws/buildbot-prometheus#11]
I recently connected the Prometheus reporter to a master instance but am receiving an error related to the step duration returning an instance of `datetime.timedelta` when trying to set a metric value. Error included below:

buildbot_1    | 2021-02-15 19:34:11+0000 [-] while invoking <bound method Prometheus.stepsConsumer of <buildbot_prometheus.prometheus.Prometheus object at 0x7f86abf43b20>>
buildbot_1    |  Traceback (most recent call last):
buildbot_1    |    File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 460, in callback
buildbot_1    |      self._startRunCallbacks(result)
buildbot_1     |    File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
buildbot_1     |      self._runCallbacks()
buildbot_1    |    File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
buildbot_1    |      current.result = callback(current.result, *args, **kw)
buildbot_1    |    File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
buildbot_1   |      _inlineCallbacks(r, g, status)
buildbot_1    |  --- <exception caught here> ---
buildbot_1   |    File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1    |      result = g.send(result)
buildbot_1   |    File "/usr/lib/python3.8/site-packages/buildbot_prometheus/prometheus.py", line 496, in stepsConsumer
buildbot_1  |      self.g_steps_duration.labels(**labels).set(duration_seconds)
buildbot_1   |    File "/usr/lib/python3.8/site-packages/prometheus_client/metrics.py", line 359, in set
buildbot_1   |      self._value.set(float(value))
buildbot_1   |  builtins.TypeError: float() argument must be a string or a number, not 'datetime.timedelta'

I am running version 2.10 of the Buildbot master and 20.4.0 of the Prometheus reporter. I have resolved this in a subclass on my current master instance 👍

**Comment by claws** [comment]
This should be resolved by #12
