### ISSUE TITLE
Installation with current pip fails

### ISSUE THREAD

**Issue by bilderbuchi** [claws/buildbot-prometheus#13]
Using pip 22.0.3 to install buildbot-prometheus master locally fails with
```
pip install .
Processing c:\users\bla\buildbot-prometheus
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\bla\buildbot-prometheus\setup.py", line 5, in <module>
          from pip.req import parse_requirements
      ModuleNotFoundError: No module named 'pip.req'

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
It seems the present setup.py is outdated, using since-removed pip API.

Modifying it to this at least installs:
```
from pip._internal.req import parse_requirements
from pip._internal.network.session import PipSession

from setuptools import setup

install_reqs = parse_requirements("requirements.txt", session=PipSession())
requires = [ir.requirement for ir in install_reqs]
```
I don't know if it's "modern usage", though - using `pip._internal` feels strange. The setup.py claims that this package supports Python 2, I guess it should be reviewed anyway... ;-)

**Comment by claws** [comment]
Thanks for taking the time to investigate and report the issue. I created this package for a personal project which has since moved on to using Github Actions so I'm not directly using it any more - but it seems others are still using it.
I'll try to fix.

**Comment by Asomiddin95** [comment]
.

**Comment by claws** [comment]
The package needed to be updated. I think problem you observed should be fixed now. 
I have uploaded the latest version (22.0.0) to PyPI.
Open the issue again if it's still a problem.

**Comment by bilderbuchi** [comment]
Thanks!
